name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI Pipeline (format, linter, tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install uv
        run: |
          pip install --upgrade pip
          pip install uv
          uv sync

      - name: Run linting with Ruff
        run: ruff check .

      - name: Run Ruff format check
        run: ruff format --check .

      - name: Run tests
        run: |
          pytest --verbose .
