name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install uv
          uv sync

          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check C++ Code Formatting with Clang-Format
        run: |
          FILES=$(find . -name "*.cpp" -o -name "*.h")
          for FILE in $FILES; do
            clang-format --dry-run --Werror $FILE || (
              echo "File $FILE is not properly formatted."
              exit 1
            )
          done

      - name: Run linting with Ruff
        run: uv run ruff check .

      - name: Run Ruff format check
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run pytest --verbose training/python/tests/
